//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessLevel
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<int> base2 { get; set; }
    }
}
