//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert
    {
        public int id { get; set; }
        public int person { get; set; }
        public int pptq { get; set; }
        public Nullable<int> questionResponse { get; set; }
        public Nullable<int> actionTaken { get; set; }
        public System.DateTime dateReceived { get; set; }
        public Nullable<System.DateTime> dateActionReported { get; set; }
        public Nullable<int> akertStatus { get; set; }
        public Nullable<int> alertReviewedBy { get; set; }
        public Nullable<int> alertApprovedBy { get; set; }
        public Nullable<System.DateTime> approvedDate { get; set; }
        public string comment { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    }
}
