//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class autoMailMessage
    {
        public autoMailMessage()
        {
            this.autoMailAttachment = new HashSet<autoMailAttachment>();
            this.automailMessagePPTQ = new HashSet<automailMessagePPTQ>();
            this.pptqAutoMailMessageLog = new HashSet<pptqAutoMailMessageLog>();
        }
    
        public int id { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string footer1 { get; set; }
        public string footer2 { get; set; }
        public int mailType { get; set; }
        public int partnerTypeTouchpointQuestionnaire { get; set; }
        public int sendDateCalcFactor { get; set; }
        public Nullable<System.DateTime> sendDateSet { get; set; }
    
        public virtual ICollection<autoMailAttachment> autoMailAttachment { get; set; }
        public virtual autoMailType autoMailType { get; set; }
        public virtual partnerTypeTouchpointQuestionnaire partnerTypeTouchpointQuestionnaire1 { get; set; }
        public virtual ICollection<automailMessagePPTQ> automailMessagePPTQ { get; set; }
        public virtual ICollection<pptqAutoMailMessageLog> pptqAutoMailMessageLog { get; set; }
    }
}
