//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class autoMail
    {
        public int id { get; set; }
        public int protocol { get; set; }
        public int touchpoint { get; set; }
        public int partnerType { get; set; }
        public int mailType { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string footer1 { get; set; }
        public string footer2 { get; set; }
    }
}
