//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class automailMessagePPTQ
    {
        public int automailMessage { get; set; }
        public int pptq { get; set; }
        public System.DateTime sentDate { get; set; }
        public int sendGridStatus { get; set; }
    
        public virtual autoMailMessage autoMailMessage1 { get; set; }
        public virtual partnerPartnertypeTouchpointQuestionnaire partnerPartnertypeTouchpointQuestionnaire { get; set; }
    }
}
