//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class autoMailType
    {
        public autoMailType()
        {
            this.autoMailMessage = new HashSet<autoMailMessage>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> oldId { get; set; }
    
        public virtual ICollection<autoMailMessage> autoMailMessage { get; set; }
    }
}
