//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;
    
    public partial class autoMailAttachment
    {
        public int id { get; set; }
        public int autoMail { get; set; }
        public string attachment { get; set; }
        public string note { get; set; }
    
        [XmlIgnore]
        [IgnoreDataMember]
        public virtual autoMailMessage autoMailMessage { get; set; }
    }
}
