//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar
    {
        public System.DateTime date_id { get; set; }
        public Nullable<short> date_year { get; set; }
        public Nullable<byte> date_month { get; set; }
        public Nullable<byte> date_day { get; set; }
        public Nullable<byte> weekday_id { get; set; }
        public string weekday_nm { get; set; }
        public string month_nm { get; set; }
        public Nullable<short> day_of_year { get; set; }
        public Nullable<byte> quarter_id { get; set; }
        public Nullable<System.DateTime> first_day_of_month { get; set; }
        public Nullable<System.DateTime> last_day_of_month { get; set; }
        public Nullable<System.DateTime> start_dts { get; set; }
        public Nullable<System.DateTime> end_dts { get; set; }
    }
}
