//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        public int id { get; set; }
        public string description { get; set; }
        public int year { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> author { get; set; }
        public Nullable<int> owner { get; set; }
        public int touchpoint { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual touchpoint touchpoint1 { get; set; }
    }
}
