//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaignRule
    {
        public int id { get; set; }
        public int campaign { get; set; }
        public int initTest { get; set; }
        public int ptqCurrent { get; set; }
        public int status { get; set; }
        public int statusLogic { get; set; }
        public int score { get; set; }
        public int scoreLogic { get; set; }
        public int responseInterval { get; set; }
        public int responseIntervalLogic { get; set; }
        public bool straightline { get; set; }
        public int delayInterval { get; set; }
        public int delayIntervalLogic { get; set; }
        public int ptqNext { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    }
}
