//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaignRule
    {
        public int id { get; set; }
        public Nullable<int> campaign { get; set; }
        public Nullable<int> initTest { get; set; }
        public Nullable<int> ptqCurrent { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> statusLogic { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> scoreLogic { get; set; }
        public Nullable<int> responseInterval { get; set; }
        public Nullable<int> responseIntervalLogic { get; set; }
        public Nullable<bool> straightline { get; set; }
        public Nullable<int> delayInterval { get; set; }
        public Nullable<int> delayIntervalLogic { get; set; }
        public Nullable<int> ptqNext { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> hardEndDate { get; set; }
        public Nullable<System.DateTime> switchOffDate { get; set; }
    }
}
