//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccr_2018
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ccr_2018()
        {
            this.ccr_2018_poc = new HashSet<ccr_2018_poc>();
        }
    
        public int id { get; set; }
        public string duns { get; set; }
        public string cageCode { get; set; }
        public Nullable<System.DateTime> dateFounded { get; set; }
        public Nullable<System.DateTime> dateForUpdate { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public Nullable<System.DateTime> dateUpdated2 { get; set; }
        public string name { get; set; }
        public string dba { get; set; }
        public string skill { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> zip4 { get; set; }
        public string country { get; set; }
        public Nullable<int> congressionalDistrict { get; set; }
        public string founded1 { get; set; }
        public string url { get; set; }
        public string state1 { get; set; }
        public string country1 { get; set; }
        public string mailingAddress { get; set; }
        public string mailingAddress2 { get; set; }
        public string mailingAddressCity { get; set; }
        public string mailingAddressZipCode { get; set; }
        public Nullable<int> mailingZip4 { get; set; }
        public string mailingAddressCountry { get; set; }
        public string mailingAddressState { get; set; }
        public string naics { get; set; }
        public Nullable<int> urlTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ccr_2018_poc> ccr_2018_poc { get; set; }
        public virtual ccr_2018_url_type ccr_2018_url_type { get; set; }
    }
}
