//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccr_2018_poc
    {
        public int id { get; set; }
        public int ccr_2018_id { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string state { get; set; }
        public string zipCode { get; set; }
        public Nullable<int> zip4 { get; set; }
        public string country { get; set; }
        public string state_1 { get; set; }
        public string phoneMain { get; set; }
        public Nullable<long> phoneExt { get; set; }
        public string phone1 { get; set; }
        public Nullable<long> phone2 { get; set; }
        public string email { get; set; }
    
        public virtual ccr_2018 ccr_2018 { get; set; }
    }
}
