//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccr_2018_tmp
    {
        public string duns { get; set; }
        public string cageCode { get; set; }
        public string dateFounded { get; set; }
        public string dateForUpdate { get; set; }
        public string dateUpdated { get; set; }
        public string dateUpdated2 { get; set; }
        public string name { get; set; }
        public string dba { get; set; }
        public string skill { get; set; }
        public string addres_1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string zip4 { get; set; }
        public string country { get; set; }
        public string congressionalDistrict { get; set; }
        public string founded1 { get; set; }
        public string url { get; set; }
        public string state1 { get; set; }
        public string country1 { get; set; }
        public string mailingAddress { get; set; }
        public string mailingAddress2 { get; set; }
        public string mailingAddressCity { get; set; }
        public string mailingAddressZipCode { get; set; }
        public string mailingZip4 { get; set; }
        public string mailingAddressCountry { get; set; }
        public string mailingAddressState { get; set; }
        public string pocFirstName_1 { get; set; }
        public string pocMiddleName_1 { get; set; }
        public string pocLastName_1 { get; set; }
        public string pocTitle_1 { get; set; }
        public string pocAddress1_1 { get; set; }
        public string pocAddress2_1 { get; set; }
        public string pocState_1 { get; set; }
        public string pocZipCode_1 { get; set; }
        public string pocZip4_1 { get; set; }
        public string pocCountry_1 { get; set; }
        public string pocState_11 { get; set; }
        public string pocPhoneMain_1 { get; set; }
        public string pocPhoneExt_1 { get; set; }
        public string pocPhone1_1 { get; set; }
        public string pocPhone2_1 { get; set; }
        public string pocEmail_1 { get; set; }
        public string pocFirstName_2 { get; set; }
        public string pocMiddleName_2 { get; set; }
        public string pocLastName_2 { get; set; }
        public string pocTitle_2 { get; set; }
        public string pocAddress1_2 { get; set; }
        public string pocAddress2_2 { get; set; }
        public string pocState_2 { get; set; }
        public string pocZipCode_2 { get; set; }
        public string pocZip4_2 { get; set; }
        public string pocCountry_2 { get; set; }
        public string pocState_21 { get; set; }
        public string pocPhone_2 { get; set; }
        public string pocPhoneExt_2 { get; set; }
        public string Blah_2 { get; set; }
        public string pocPhone2_2 { get; set; }
        public string pocEmail_2 { get; set; }
        public string pocFirstName_3 { get; set; }
        public string pocMiddleName_3 { get; set; }
        public string pocLastName_3 { get; set; }
        public string pocTitle_3 { get; set; }
        public string pocAddress1_3 { get; set; }
        public string pocAddress2_3 { get; set; }
        public string pocState_3 { get; set; }
        public string pocZipCode_3 { get; set; }
        public string pocZip4_3 { get; set; }
        public string pocCountry_3 { get; set; }
        public string pocState_31 { get; set; }
        public string pocPhone_3 { get; set; }
        public string pocPhone2_3 { get; set; }
        public string pocEmail_3 { get; set; }
        public string pocFirstName_4 { get; set; }
        public string pocMiddleName_4 { get; set; }
        public string pocLastName_4 { get; set; }
        public string pocTitle_4 { get; set; }
        public string pocAddress1_4 { get; set; }
        public string pocAddress2_4 { get; set; }
        public string pocState_4 { get; set; }
        public string pocZipCode_4 { get; set; }
        public string pocZip4_4 { get; set; }
        public string pocCountry_4 { get; set; }
        public string pocState_41 { get; set; }
        public string pocPhone_4 { get; set; }
        public string pocPhone2_4 { get; set; }
        public string pocEmail_4 { get; set; }
        public string pocFirstName_5 { get; set; }
        public string pocMiddleName_5 { get; set; }
        public string pocLastName_5 { get; set; }
        public string pocTitle_5 { get; set; }
        public string pocAddress1_5 { get; set; }
        public string pocAddress2_5 { get; set; }
        public string pocState_5 { get; set; }
        public string pocZipCode_5 { get; set; }
        public string pocZip4_5 { get; set; }
        public string pocCountry_5 { get; set; }
        public string pocState_51 { get; set; }
        public string pocPhone_5 { get; set; }
        public string pocPhone2_5 { get; set; }
        public string pocEmail_5 { get; set; }
        public string pocFirstName_6 { get; set; }
        public string pocMiddleName_6 { get; set; }
        public string pocLastName_6 { get; set; }
        public string pocTitle_6 { get; set; }
        public string pocAddress1_6 { get; set; }
        public string pocAddress2_6 { get; set; }
        public string pocState_6 { get; set; }
        public string pocZipCode_6 { get; set; }
        public string pocZip4_6 { get; set; }
        public string pocCountry_6 { get; set; }
        public string pocState_61 { get; set; }
        public string pocPhone_6 { get; set; }
        public string pocPhone2_6 { get; set; }
        public string pocEmail_6 { get; set; }
        public string temp { get; set; }
        public int id { get; set; }
    }
}
