//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyProfileDataLoad
    {
        public int id { get; set; }
        public string companyName { get; set; }
        public string jobAddress { get; set; }
        public string jobCity { get; set; }
        public string jobState { get; set; }
        public string jobZicode { get; set; }
        public string jobCountry { get; set; }
        public string jobSnippet { get; set; }
        public string companyMainNumber { get; set; }
        public string companyURL { get; set; }
        public string searchterm { get; set; }
        public Nullable<long> pocPhoneNumber { get; set; }
        public string pocFirstName { get; set; }
        public string pocLastName { get; set; }
        public string pocTitle { get; set; }
        public string pocEmailAddress { get; set; }
        public string companyRevenue { get; set; }
        public string companyEmployeeCount { get; set; }
        public string industrySector { get; set; }
        public Nullable<int> relationshipOwner { get; set; }
        public Nullable<int> pptq { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    }
}
