//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class confirmationSpreadsheetDataLoad
    {
        public int id { get; set; }
        public int pptq_A { get; set; }
        public int pptq_B_Reference { get; set; }
        public int ptq { get; set; }
        public int action { get; set; }
    }
}
