//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.enterpriseContactUs = new HashSet<enterpriseContactUs>();
        }
    
        public int id { get; set; }
        public Nullable<int> eplsCountryID { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string governanceCode { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> enterprise { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        public virtual ICollection<enterpriseContactUs> enterpriseContactUs { get; set; }
    }
}
