//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterpriseContactUs
    {
        public int enterprise { get; set; }
        public int protocol { get; set; }
        public int touchpoint { get; set; }
        public int partnertype { get; set; }
        public int group { get; set; }
        public int country { get; set; }
    
        public virtual country country1 { get; set; }
        public virtual enterprise enterprise1 { get; set; }
        public virtual group group1 { get; set; }
        public virtual partnerType partnerType1 { get; set; }
        public virtual protocol protocol1 { get; set; }
        public virtual touchpoint touchpoint1 { get; set; }
    }
}
