//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise()
        {
            this.agency = new HashSet<agency>();
            this.country = new HashSet<country>();
            this.enterpriseObjectName = new HashSet<enterpriseObjectName>();
            this.enterpriseSystemInfo = new HashSet<enterpriseSystemInfo>();
            this.group = new HashSet<group>();
            this.groupCollection = new HashSet<groupCollection>();
            this.hs3Menu_deprecated = new HashSet<hs3Menu_deprecated>();
            this.key = new HashSet<key>();
            this.language = new HashSet<language>();
            this.languageInfo = new HashSet<languageInfo>();
            this.UM_M_Menu_deprecated = new HashSet<UM_M_Menu_deprecated>();
            this.menu = new HashSet<menu>();
            this.partner = new HashSet<partner>();
            this.partnerType = new HashSet<partnerType>();
            this.person = new HashSet<person>();
            this.protocol = new HashSet<protocol>();
            this.role = new HashSet<role>();
            this.rule = new HashSet<rule>();
            this.ruleType = new HashSet<ruleType>();
            this.state = new HashSet<state>();
            this.site = new HashSet<site>();
            this.questionnaireLevelType = new HashSet<questionnaireLevelType>();
            this.menu1 = new HashSet<menu>();
            this.partnumberSpreadsheetDataLoad = new HashSet<partnumberSpreadsheetDataLoad>();
            this.partnerSpreadsheetDataLoads = new HashSet<partnerSpreadsheetDataLoad>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public byte[] logo { get; set; }
        public string applicationPath { get; set; }
        public string companyName { get; set; }
        public string instanceName { get; set; }
        public Nullable<System.DateTime> archivedDate { get; set; }
        public Nullable<int> userMax { get; set; }
        public Nullable<int> partnerMax { get; set; }
        public Nullable<int> partnumberMax { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> subscriptionType { get; set; }
        public Nullable<System.DateTime> freeTrialStartDate { get; set; }
        public Nullable<System.DateTime> freeTrialEndDate { get; set; }
        public Nullable<System.DateTime> licenseStartDate { get; set; }
        public Nullable<System.DateTime> licenseEndDate { get; set; }
        public Nullable<decimal> monthlyFee { get; set; }
        public Nullable<int> subscriptionStatus { get; set; }
        public string chargifyID { get; set; }
        public Nullable<int> multiTenantProjectType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agency> agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<country> country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterpriseObjectName> enterpriseObjectName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterpriseSystemInfo> enterpriseSystemInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group> group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupCollection> groupCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hs3Menu_deprecated> hs3Menu_deprecated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<key> key { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<language> language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<languageInfo> languageInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_M_Menu_deprecated> UM_M_Menu_deprecated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner> partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnerType> partnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<person> person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<protocol> protocol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rule> rule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruleType> ruleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<state> state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site> site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionnaireLevelType> questionnaireLevelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnumberSpreadsheetDataLoad> partnumberSpreadsheetDataLoad { get; set; }
        public virtual enterpriseContactUs enterpriseContactUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnerSpreadsheetDataLoad> partnerSpreadsheetDataLoads { get; set; }
    }
}
