//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterpriseSystemInfo
    {
        public int id { get; set; }
        public Nullable<System.DateTime> systemExpiry { get; set; }
        public Nullable<int> licenseLimit { get; set; }
        public string companyName { get; set; }
        public string contractCoordinator { get; set; }
        public string companyWebSite { get; set; }
        public string coordinatorEmail { get; set; }
        public Nullable<int> isCurrentDataBase { get; set; }
        public string logoImage { get; set; }
        public bool configured { get; set; }
        public Nullable<int> enterprise { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
    }
}
