//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterpriseSpreadsheetDataLoad
    {
        public int id { get; set; }
        public string emailAddress { get; set; }
        public string companyName { get; set; }
        public string companyURL { get; set; }
        public int industry { get; set; }
        public int focus { get; set; }
        public bool agreedToTerms { get; set; }
        public int subscriptionType { get; set; }
        public Nullable<int> enterprise { get; set; }
        public int status { get; set; }
    }
}
