//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise
    {
        public enterprise()
        {
            this.enterpriseObjectNames = new HashSet<enterpriseObjectName>();
            this.enterpriseSystemInfoes = new HashSet<enterpriseSystemInfo>();
            this.people = new HashSet<person>();
            this.roles = new HashSet<role>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public string logo { get; set; }
        public string applicationPath { get; set; }
        public string companyName { get; set; }
        public string instanceName { get; set; }
        public Nullable<System.DateTime> archivedDate { get; set; }
    
        public virtual ICollection<enterpriseObjectName> enterpriseObjectNames { get; set; }
        public virtual ICollection<enterpriseSystemInfo> enterpriseSystemInfoes { get; set; }
        public virtual ICollection<person> people { get; set; }
        public virtual ICollection<role> roles { get; set; }
    }
}
