//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterpriseLandingPagePTQ
    {
        public int enterprise { get; set; }
        public int landingPage { get; set; }
        public string text { get; set; }
        public int partnertypeTouchpointQuestionnaire { get; set; }
    }
}
