//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class eSignature
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string affirmation { get; set; }
        public string officer { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> completeDate { get; set; }
        public int partnerPartnerTypeTouchpointQuestionnaire { get; set; }
    
        public virtual partnerPartnertypeTouchpointQuestionnaire partnerPartnertypeTouchpointQuestionnaire1 { get; set; }
    }
}
