//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventNotification
    {
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string @event { get; set; }
        public string reason { get; set; }
        public string url { get; set; }
        public string category { get; set; }
        public string accesscode { get; set; }
        public string protocolTouchpoint { get; set; }
        public string applicationName { get; set; }
        public Nullable<int> enterprise { get; set; }
        public string loadgroup { get; set; }
    }
}
