//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class far
    {
        public int partner { get; set; }
        public string description { get; set; }
        public string documentType { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    }
}
