//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class foiaContactList2015
    {
        public Nullable<int> id { get; set; }
        public string dateAdded { get; set; }
        public string dateUpdated { get; set; }
        public string partnerName { get; set; }
        public string url { get; set; }
        public Nullable<int> employeeCount { get; set; }
        public Nullable<long> revenue { get; set; }
        public Nullable<double> dateFounded { get; set; }
        public string naics { get; set; }
        public string businessArea { get; set; }
        public string fullname { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
