//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class foia_2016_poc
    {
        public int id { get; set; }
        public Nullable<int> parent { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string title { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string duns2 { get; set; }
    
        public virtual foia_2016 foia_2016 { get; set; }
    }
}
