//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class foiaContact
    {
        public int id { get; set; }
        public Nullable<int> partner { get; set; }
        public string fullname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string poc1Country { get; set; }
        public string state { get; set; }
        public string phone { get; set; }
        public Nullable<double> poc1PhoneExt { get; set; }
        public Nullable<double> poc1AltPhone { get; set; }
        public string fax { get; set; }
        public string poc1Email { get; set; }
    }
}
