//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class group
    {
        public group()
        {
            this.partner = new HashSet<partner>();
            this.person1 = new HashSet<person>();
        }
    
        public int id { get; set; }
        public Nullable<int> enterprise { get; set; }
         [Required]
        public int groupCollection { get; set; }

        public Nullable<int> groupType { get; set; }
        public Nullable<int> author { get; set; }
        public Nullable<int> state { get; set; }
          [Required]
        public string name { get; set; }
        [Required]
        public string description { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        public virtual groupCollection groupCollection1 { get; set; }
        public virtual person person { get; set; }
        public virtual ICollection<partner> partner { get; set; }
        public virtual ICollection<person> person1 { get; set; }
    }
}
