//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupRiskGoal
    {
        public int id { get; set; }
        public int group { get; set; }
        public int touchpoint { get; set; }
        public Nullable<int> C0to10th { get; set; }
        public Nullable<int> C10to25 { get; set; }
        public Nullable<int> C25to50 { get; set; }
        public Nullable<int> C50to75 { get; set; }
        public Nullable<int> C75to90 { get; set; }
        public Nullable<int> C90to100 { get; set; }
        public string RangeTypeGroup { get; set; }
    }
}
