//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HricRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HricRegistration()
        {
            this.HricRegistrationEvents = new HashSet<HricRegistrationEvent>();
        }
    
        public int id { get; set; }
        public int pptq { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string ProductTier { get; set; }
        public string Status { get; set; }
        public string QuestionnaireLink { get; set; }
        public Nullable<System.DateTime> LinkExpiresAtUtc { get; set; }
        public string IdempotencyKey { get; set; }
        public string Source { get; set; }
        public string RedirectBaseUrl { get; set; }
        public string Locale { get; set; }
        public System.DateTime CreatedAtUtc { get; set; }
        public System.DateTime UpdatedAtUtc { get; set; }
    
        public virtual partnerPartnertypeTouchpointQuestionnaire partnerPartnertypeTouchpointQuestionnaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HricRegistrationEvent> HricRegistrationEvents { get; set; }
    }
}
