//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HricRegistrationEvent
    {
        public int id { get; set; }
        public int HricRegistration_id { get; set; }
        public string EventExternalId { get; set; }
        public string Type { get; set; }
        public System.DateTime OccurredAtUtc { get; set; }
        public string PayloadJson { get; set; }
    
        public virtual HricRegistration HricRegistration { get; set; }
    }
}
