//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs3Menu
    {
        public int id { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> grand { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> accesslevel { get; set; }
        public Nullable<int> menuGroup { get; set; }
        public Nullable<bool> isDynamicCreated { get; set; }
        public Nullable<int> device { get; set; }
    }
}
