//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class hs3MVCMTQa2Entities : DbContext
    {
        public hs3MVCMTQa2Entities()
            : base("name=hs3MVCMTQa2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accessLevel> accessLevels { get; set; }
        public DbSet<enterprise> enterprises { get; set; }
        public DbSet<enterpriseObjectName> enterpriseObjectNames { get; set; }
        public DbSet<enterpriseSystemInfo> enterpriseSystemInfoes { get; set; }
        public DbSet<hs3Menu> hs3Menu { get; set; }
        public DbSet<letter> letters { get; set; }
        public DbSet<letterSeed> letterSeeds { get; set; }
        public DbSet<loadHistory> loadHistories { get; set; }
        public DbSet<menuAccessLevel> menuAccessLevels { get; set; }
        public DbSet<menuGroup> menuGroups { get; set; }
        public DbSet<numberSeed> numberSeeds { get; set; }
        public DbSet<person> people { get; set; }
        public DbSet<personLoginAudit> personLoginAudits { get; set; }
        public DbSet<personLoginAuditEvent> personLoginAuditEvents { get; set; }
        public DbSet<personRelationshipType> personRelationshipTypes { get; set; }
        public DbSet<personSearchCount> personSearchCounts { get; set; }
        public DbSet<personStatu> personStatus { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int GenerateSPforInsertUpdateDelete2(string schemaname, string tablename, string procName, Nullable<bool> identityInsert)
        {
            var schemanameParameter = schemaname != null ?
                new ObjectParameter("Schemaname", schemaname) :
                new ObjectParameter("Schemaname", typeof(string));
    
            var tablenameParameter = tablename != null ?
                new ObjectParameter("Tablename", tablename) :
                new ObjectParameter("Tablename", typeof(string));
    
            var procNameParameter = procName != null ?
                new ObjectParameter("ProcName", procName) :
                new ObjectParameter("ProcName", typeof(string));
    
            var identityInsertParameter = identityInsert.HasValue ?
                new ObjectParameter("IdentityInsert", identityInsert) :
                new ObjectParameter("IdentityInsert", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateSPforInsertUpdateDelete2", schemanameParameter, tablenameParameter, procNameParameter, identityInsertParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pr_addEnterprise(string description, Nullable<int> sortOrder, Nullable<bool> active, string logo, string applicationPath, string companyName, string instanceName, Nullable<System.DateTime> archivedDate, Nullable<int> id)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            var logoParameter = logo != null ?
                new ObjectParameter("logo", logo) :
                new ObjectParameter("logo", typeof(string));
    
            var applicationPathParameter = applicationPath != null ?
                new ObjectParameter("applicationPath", applicationPath) :
                new ObjectParameter("applicationPath", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var instanceNameParameter = instanceName != null ?
                new ObjectParameter("instanceName", instanceName) :
                new ObjectParameter("instanceName", typeof(string));
    
            var archivedDateParameter = archivedDate.HasValue ?
                new ObjectParameter("archivedDate", archivedDate) :
                new ObjectParameter("archivedDate", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pr_addEnterprise", descriptionParameter, sortOrderParameter, activeParameter, logoParameter, applicationPathParameter, companyNameParameter, instanceNameParameter, archivedDateParameter, idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pr_addEnterpriseSystemInfo(Nullable<System.DateTime> systemExpiry, Nullable<int> licenseLimit, string companyName, string contractCoordinator, string companyWebSite, string coordinatorEmail, Nullable<int> isCurrentDataBase, string logoImage, Nullable<bool> configured, Nullable<int> enterprise)
        {
            var systemExpiryParameter = systemExpiry.HasValue ?
                new ObjectParameter("systemExpiry", systemExpiry) :
                new ObjectParameter("systemExpiry", typeof(System.DateTime));
    
            var licenseLimitParameter = licenseLimit.HasValue ?
                new ObjectParameter("licenseLimit", licenseLimit) :
                new ObjectParameter("licenseLimit", typeof(int));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var contractCoordinatorParameter = contractCoordinator != null ?
                new ObjectParameter("contractCoordinator", contractCoordinator) :
                new ObjectParameter("contractCoordinator", typeof(string));
    
            var companyWebSiteParameter = companyWebSite != null ?
                new ObjectParameter("companyWebSite", companyWebSite) :
                new ObjectParameter("companyWebSite", typeof(string));
    
            var coordinatorEmailParameter = coordinatorEmail != null ?
                new ObjectParameter("coordinatorEmail", coordinatorEmail) :
                new ObjectParameter("coordinatorEmail", typeof(string));
    
            var isCurrentDataBaseParameter = isCurrentDataBase.HasValue ?
                new ObjectParameter("isCurrentDataBase", isCurrentDataBase) :
                new ObjectParameter("isCurrentDataBase", typeof(int));
    
            var logoImageParameter = logoImage != null ?
                new ObjectParameter("logoImage", logoImage) :
                new ObjectParameter("logoImage", typeof(string));
    
            var configuredParameter = configured.HasValue ?
                new ObjectParameter("configured", configured) :
                new ObjectParameter("configured", typeof(bool));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pr_addEnterpriseSystemInfo", systemExpiryParameter, licenseLimitParameter, companyNameParameter, contractCoordinatorParameter, companyWebSiteParameter, coordinatorEmailParameter, isCurrentDataBaseParameter, logoImageParameter, configuredParameter, enterpriseParameter);
        }
    
        public virtual int pr_addPerson(Nullable<int> enterprise, Nullable<int> role, Nullable<int> manager, Nullable<int> personStatus, Nullable<int> riskType, Nullable<int> loadHistory, Nullable<int> campaign, string internalId, string nmNumber, string socialSecurity, string firstName, string lastName, string title, string suffix, string nickName, string passWord, string email, string address1, string address2, string city, Nullable<int> state, string zipcode, Nullable<int> country, string phone, string fax, Nullable<int> active, Nullable<int> ismanager, Nullable<int> partnerPerPage, Nullable<System.DateTime> resetDate, Nullable<bool> isArchived1, Nullable<System.DateTime> archivedDate)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            var managerParameter = manager.HasValue ?
                new ObjectParameter("manager", manager) :
                new ObjectParameter("manager", typeof(int));
    
            var personStatusParameter = personStatus.HasValue ?
                new ObjectParameter("personStatus", personStatus) :
                new ObjectParameter("personStatus", typeof(int));
    
            var riskTypeParameter = riskType.HasValue ?
                new ObjectParameter("riskType", riskType) :
                new ObjectParameter("riskType", typeof(int));
    
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            var campaignParameter = campaign.HasValue ?
                new ObjectParameter("campaign", campaign) :
                new ObjectParameter("campaign", typeof(int));
    
            var internalIdParameter = internalId != null ?
                new ObjectParameter("internalId", internalId) :
                new ObjectParameter("internalId", typeof(string));
    
            var nmNumberParameter = nmNumber != null ?
                new ObjectParameter("nmNumber", nmNumber) :
                new ObjectParameter("nmNumber", typeof(string));
    
            var socialSecurityParameter = socialSecurity != null ?
                new ObjectParameter("socialSecurity", socialSecurity) :
                new ObjectParameter("socialSecurity", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var suffixParameter = suffix != null ?
                new ObjectParameter("suffix", suffix) :
                new ObjectParameter("suffix", typeof(string));
    
            var nickNameParameter = nickName != null ?
                new ObjectParameter("nickName", nickName) :
                new ObjectParameter("nickName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("passWord", passWord) :
                new ObjectParameter("passWord", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("zipcode", zipcode) :
                new ObjectParameter("zipcode", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(int));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(int));
    
            var ismanagerParameter = ismanager.HasValue ?
                new ObjectParameter("ismanager", ismanager) :
                new ObjectParameter("ismanager", typeof(int));
    
            var partnerPerPageParameter = partnerPerPage.HasValue ?
                new ObjectParameter("partnerPerPage", partnerPerPage) :
                new ObjectParameter("partnerPerPage", typeof(int));
    
            var resetDateParameter = resetDate.HasValue ?
                new ObjectParameter("resetDate", resetDate) :
                new ObjectParameter("resetDate", typeof(System.DateTime));
    
            var isArchived1Parameter = isArchived1.HasValue ?
                new ObjectParameter("IsArchived1", isArchived1) :
                new ObjectParameter("IsArchived1", typeof(bool));
    
            var archivedDateParameter = archivedDate.HasValue ?
                new ObjectParameter("archivedDate", archivedDate) :
                new ObjectParameter("archivedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_addPerson", enterpriseParameter, roleParameter, managerParameter, personStatusParameter, riskTypeParameter, loadHistoryParameter, campaignParameter, internalIdParameter, nmNumberParameter, socialSecurityParameter, firstNameParameter, lastNameParameter, titleParameter, suffixParameter, nickNameParameter, passWordParameter, emailParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, zipcodeParameter, countryParameter, phoneParameter, faxParameter, activeParameter, ismanagerParameter, partnerPerPageParameter, resetDateParameter, isArchived1Parameter, archivedDateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pr_addPersonStatus(string description, Nullable<int> sortOrder, Nullable<bool> active)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pr_addPersonStatus", descriptionParameter, sortOrderParameter, activeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pr_addRole(string description, Nullable<int> sortOrder, Nullable<int> active, Nullable<int> accessLevel, Nullable<int> enterprise, Nullable<int> access)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(int));
    
            var accessLevelParameter = accessLevel.HasValue ?
                new ObjectParameter("accessLevel", accessLevel) :
                new ObjectParameter("accessLevel", typeof(int));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var accessParameter = access.HasValue ?
                new ObjectParameter("access", access) :
                new ObjectParameter("access", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pr_addRole", descriptionParameter, sortOrderParameter, activeParameter, accessLevelParameter, enterpriseParameter, accessParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr_addUserRole(Nullable<int> accessLevel, string description, Nullable<int> enterprise, Nullable<int> access)
        {
            var accessLevelParameter = accessLevel.HasValue ?
                new ObjectParameter("accessLevel", accessLevel) :
                new ObjectParameter("accessLevel", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var accessParameter = access.HasValue ?
                new ObjectParameter("access", access) :
                new ObjectParameter("access", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr_addUserRole", accessLevelParameter, descriptionParameter, enterpriseParameter, accessParameter);
        }
    
        public virtual int pr_archiveEnterprise(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_archiveEnterprise", idParameter);
        }
    
        public virtual int pr_archivePerson(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_archivePerson", idParameter);
        }
    
        public virtual int pr_archivePersonStatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_archivePersonStatus", idParameter);
        }
    
        public virtual int pr_archiveRole(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_archiveRole", idParameter);
        }
    
        public virtual ObjectResult<pr_doLogin_Result> pr_doLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_doLogin_Result>("pr_doLogin", usernameParameter, passwordParameter);
        }
    
        public virtual int pr_findPerson(Nullable<int> enterprise, string selected_sql)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var selected_sqlParameter = selected_sql != null ?
                new ObjectParameter("selected_sql", selected_sql) :
                new ObjectParameter("selected_sql", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_findPerson", enterpriseParameter, selected_sqlParameter);
        }
    
        public virtual ObjectResult<pr_findUserRole_Result> pr_findUserRole(Nullable<int> enterprise, string userRole)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_findUserRole_Result>("pr_findUserRole", enterpriseParameter, userRoleParameter);
        }
    
        public virtual int pr_getAccesscode(ObjectParameter access)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getAccesscode", access);
        }
    
        public virtual ObjectResult<pr_getEnterprise_Result> pr_getEnterprise(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getEnterprise_Result>("pr_getEnterprise", enterpriseParameter);
        }
    
        public virtual ObjectResult<pr_getObjectNameByEnterprise_Result> pr_getObjectNameByEnterprise(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getObjectNameByEnterprise_Result>("pr_getObjectNameByEnterprise", enterpriseParameter);
        }
    
        public virtual ObjectResult<pr_getObjectNameByEnterpriseForMobile_Result> pr_getObjectNameByEnterpriseForMobile(Nullable<int> enterprise, Nullable<int> device)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var deviceParameter = device.HasValue ?
                new ObjectParameter("Device", device) :
                new ObjectParameter("Device", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getObjectNameByEnterpriseForMobile_Result>("pr_getObjectNameByEnterpriseForMobile", enterpriseParameter, deviceParameter);
        }
    
        public virtual ObjectResult<pr_getObjectNameByEnterpriseObjectName_Result> pr_getObjectNameByEnterpriseObjectName(Nullable<int> enterprise, string objectName)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var objectNameParameter = objectName != null ?
                new ObjectParameter("objectName", objectName) :
                new ObjectParameter("objectName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getObjectNameByEnterpriseObjectName_Result>("pr_getObjectNameByEnterpriseObjectName", enterpriseParameter, objectNameParameter);
        }
    
        public virtual ObjectResult<pr_getPerson_Result> pr_getPerson(Nullable<int> person)
        {
            var personParameter = person.HasValue ?
                new ObjectParameter("person", person) :
                new ObjectParameter("person", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPerson_Result>("pr_getPerson", personParameter);
        }
    
        public virtual ObjectResult<pr_getPersonAll_Result> pr_getPersonAll(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonAll_Result>("pr_getPersonAll", enterpriseParameter);
        }
    
        public virtual ObjectResult<pr_getPersonAllConfirmed_Result> pr_getPersonAllConfirmed(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonAllConfirmed_Result>("pr_getPersonAllConfirmed", enterpriseParameter);
        }
    
        public virtual ObjectResult<pr_getPersonByEmail_Result> pr_getPersonByEmail(string email, Nullable<int> enterprise)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonByEmail_Result>("pr_getPersonByEmail", emailParameter, enterpriseParameter);
        }
    
        public virtual ObjectResult<pr_getPersonByEmailForLoginAttemps_Result> pr_getPersonByEmailForLoginAttemps(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonByEmailForLoginAttemps_Result>("pr_getPersonByEmailForLoginAttemps", emailParameter);
        }
    
        public virtual ObjectResult<pr_getPersonByInternalID_Result> pr_getPersonByInternalID(string internalID)
        {
            var internalIDParameter = internalID != null ?
                new ObjectParameter("internalID", internalID) :
                new ObjectParameter("internalID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonByInternalID_Result>("pr_getPersonByInternalID", internalIDParameter);
        }
    
        public virtual ObjectResult<pr_getPersonByInternalIDEmail_Result> pr_getPersonByInternalIDEmail(string internalID, string email)
        {
            var internalIDParameter = internalID != null ?
                new ObjectParameter("internalID", internalID) :
                new ObjectParameter("internalID", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonByInternalIDEmail_Result>("pr_getPersonByInternalIDEmail", internalIDParameter, emailParameter);
        }
    
        public virtual ObjectResult<pr_getPersonByLoadHistory_Result> pr_getPersonByLoadHistory(Nullable<int> loadHistory)
        {
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonByLoadHistory_Result>("pr_getPersonByLoadHistory", loadHistoryParameter);
        }
    
        public virtual ObjectResult<pr_getPersonByStatus_Result> pr_getPersonByStatus(Nullable<int> status, Nullable<int> loadHistory, Nullable<int> enterprise)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonByStatus_Result>("pr_getPersonByStatus", statusParameter, loadHistoryParameter, enterpriseParameter);
        }
    
        public virtual ObjectResult<pr_getPersonColumnHeader_Result> pr_getPersonColumnHeader()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonColumnHeader_Result>("pr_getPersonColumnHeader");
        }
    
        public virtual ObjectResult<pr_getPersonColumnNameByID_Result> pr_getPersonColumnNameByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonColumnNameByID_Result>("pr_getPersonColumnNameByID", idParameter);
        }
    
        public virtual ObjectResult<pr_getPersonCountByAllRole_Result> pr_getPersonCountByAllRole(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonCountByAllRole_Result>("pr_getPersonCountByAllRole", enterpriseParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr_getPersonCountByRole(Nullable<int> enterprise, Nullable<int> role)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr_getPersonCountByRole", enterpriseParameter, roleParameter);
        }
    
        public virtual ObjectResult<pr_getPersonDupByEmail_Result> pr_getPersonDupByEmail(Nullable<int> loadHistory)
        {
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonDupByEmail_Result>("pr_getPersonDupByEmail", loadHistoryParameter);
        }
    
        public virtual ObjectResult<pr_getPersonDupByInternalID_Result> pr_getPersonDupByInternalID(Nullable<int> loadHistory)
        {
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonDupByInternalID_Result>("pr_getPersonDupByInternalID", loadHistoryParameter);
        }
    
        public virtual int pr_getPersonEmailCount(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getPersonEmailCount", emailParameter);
        }
    
        public virtual ObjectResult<pr_getPersonExcel_Result> pr_getPersonExcel(Nullable<int> loadHistory)
        {
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonExcel_Result>("pr_getPersonExcel", loadHistoryParameter);
        }
    
        public virtual int pr_getPersonExcelByAuthor(Nullable<int> person)
        {
            var personParameter = person.HasValue ?
                new ObjectParameter("person", person) :
                new ObjectParameter("person", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getPersonExcelByAuthor", personParameter);
        }
    
        public virtual ObjectResult<pr_getPersonExcelByEmail_Result> pr_getPersonExcelByEmail(string email, Nullable<int> loadHistory)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonExcelByEmail_Result>("pr_getPersonExcelByEmail", emailParameter, loadHistoryParameter);
        }
    
        public virtual ObjectResult<pr_getPersonExcelByInternalID_Result> pr_getPersonExcelByInternalID(string internalID, Nullable<int> loadHistory)
        {
            var internalIDParameter = internalID != null ?
                new ObjectParameter("internalID", internalID) :
                new ObjectParameter("internalID", typeof(string));
    
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonExcelByInternalID_Result>("pr_getPersonExcelByInternalID", internalIDParameter, loadHistoryParameter);
        }
    
        public virtual ObjectResult<pr_getPersonExcelDupByEmail_Result> pr_getPersonExcelDupByEmail(Nullable<int> loadHistory)
        {
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonExcelDupByEmail_Result>("pr_getPersonExcelDupByEmail", loadHistoryParameter);
        }
    
        public virtual ObjectResult<pr_getPersonExcelDupByInternalID_Result> pr_getPersonExcelDupByInternalID(Nullable<int> loadHistory)
        {
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonExcelDupByInternalID_Result>("pr_getPersonExcelDupByInternalID", loadHistoryParameter);
        }
    
        public virtual int pr_getPersonInfoByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getPersonInfoByID", idParameter);
        }
    
        public virtual int pr_getPersonInternalIDCount(string internalID)
        {
            var internalIDParameter = internalID != null ?
                new ObjectParameter("internalID", internalID) :
                new ObjectParameter("internalID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getPersonInternalIDCount", internalIDParameter);
        }
    
        public virtual ObjectResult<string> pr_getPersonNameById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_getPersonNameById", idParameter);
        }
    
        public virtual int pr_getPersonPartnerCount(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getPersonPartnerCount", enterpriseParameter);
        }
    
        public virtual int pr_getPersonPartnerCountByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getPersonPartnerCountByID", idParameter);
        }
    
        public virtual ObjectResult<pr_getPersonPreviousNext_Result> pr_getPersonPreviousNext(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonPreviousNext_Result>("pr_getPersonPreviousNext", idParameter);
        }
    
        public virtual ObjectResult<pr_getPersonPwdByEmail_Result> pr_getPersonPwdByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonPwdByEmail_Result>("pr_getPersonPwdByEmail", emailParameter);
        }
    
        public virtual ObjectResult<pr_getPersonRoleAll_Result> pr_getPersonRoleAll(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getPersonRoleAll_Result>("pr_getPersonRoleAll", enterpriseParameter);
        }
    
        public virtual int pr_getRole(string roleName, ObjectParameter id)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("roleName", roleName) :
                new ObjectParameter("roleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getRole", roleNameParameter, id);
        }
    
        public virtual ObjectResult<Nullable<int>> pr_getRoleAccessByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr_getRoleAccessByID", idParameter);
        }
    
        public virtual ObjectResult<pr_getRoleAll_Result> pr_getRoleAll(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getRoleAll_Result>("pr_getRoleAll", enterpriseParameter);
        }
    
        public virtual ObjectResult<string> pr_getRoleByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_getRoleByID", idParameter);
        }
    
        public virtual ObjectResult<pr_getRoleByName_Result> pr_getRoleByName(string roleName, Nullable<int> enterprise)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("roleName", roleName) :
                new ObjectParameter("roleName", typeof(string));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_getRoleByName_Result>("pr_getRoleByName", roleNameParameter, enterpriseParameter);
        }
    
        public virtual int pr_getStateAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getStateAll");
        }
    
        public virtual int pr_getStateByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getStateByID", idParameter);
        }
    
        public virtual int pr_getStateByName(string stateName)
        {
            var stateNameParameter = stateName != null ?
                new ObjectParameter("stateName", stateName) :
                new ObjectParameter("stateName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getStateByName", stateNameParameter);
        }
    
        public virtual int pr_getStateName(Nullable<int> id, ObjectParameter stateName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getStateName", idParameter, stateName);
        }
    
        public virtual int pr_getSystemInfo(Nullable<int> enterprise)
        {
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_getSystemInfo", enterpriseParameter);
        }
    
        public virtual int pr_modifyEnterprise(string description, Nullable<int> sortOrder, Nullable<bool> active, string logo, string applicationPath, string companyName, string instanceName, Nullable<System.DateTime> archivedDate, Nullable<int> id)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            var logoParameter = logo != null ?
                new ObjectParameter("logo", logo) :
                new ObjectParameter("logo", typeof(string));
    
            var applicationPathParameter = applicationPath != null ?
                new ObjectParameter("applicationPath", applicationPath) :
                new ObjectParameter("applicationPath", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var instanceNameParameter = instanceName != null ?
                new ObjectParameter("instanceName", instanceName) :
                new ObjectParameter("instanceName", typeof(string));
    
            var archivedDateParameter = archivedDate.HasValue ?
                new ObjectParameter("archivedDate", archivedDate) :
                new ObjectParameter("archivedDate", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyEnterprise", descriptionParameter, sortOrderParameter, activeParameter, logoParameter, applicationPathParameter, companyNameParameter, instanceNameParameter, archivedDateParameter, idParameter);
        }
    
        public virtual int pr_modifyEnterpriseSystemInfo(Nullable<System.DateTime> systemExpiry, Nullable<int> licenseLimit, string companyName, string contractCoordinator, string companyWebSite, string coordinatorEmail, Nullable<int> isCurrentDataBase, string logoImage, Nullable<bool> configured, Nullable<int> enterprise, Nullable<int> id)
        {
            var systemExpiryParameter = systemExpiry.HasValue ?
                new ObjectParameter("systemExpiry", systemExpiry) :
                new ObjectParameter("systemExpiry", typeof(System.DateTime));
    
            var licenseLimitParameter = licenseLimit.HasValue ?
                new ObjectParameter("licenseLimit", licenseLimit) :
                new ObjectParameter("licenseLimit", typeof(int));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var contractCoordinatorParameter = contractCoordinator != null ?
                new ObjectParameter("contractCoordinator", contractCoordinator) :
                new ObjectParameter("contractCoordinator", typeof(string));
    
            var companyWebSiteParameter = companyWebSite != null ?
                new ObjectParameter("companyWebSite", companyWebSite) :
                new ObjectParameter("companyWebSite", typeof(string));
    
            var coordinatorEmailParameter = coordinatorEmail != null ?
                new ObjectParameter("coordinatorEmail", coordinatorEmail) :
                new ObjectParameter("coordinatorEmail", typeof(string));
    
            var isCurrentDataBaseParameter = isCurrentDataBase.HasValue ?
                new ObjectParameter("isCurrentDataBase", isCurrentDataBase) :
                new ObjectParameter("isCurrentDataBase", typeof(int));
    
            var logoImageParameter = logoImage != null ?
                new ObjectParameter("logoImage", logoImage) :
                new ObjectParameter("logoImage", typeof(string));
    
            var configuredParameter = configured.HasValue ?
                new ObjectParameter("configured", configured) :
                new ObjectParameter("configured", typeof(bool));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyEnterpriseSystemInfo", systemExpiryParameter, licenseLimitParameter, companyNameParameter, contractCoordinatorParameter, companyWebSiteParameter, coordinatorEmailParameter, isCurrentDataBaseParameter, logoImageParameter, configuredParameter, enterpriseParameter, idParameter);
        }
    
        public virtual int pr_modifyPerson(Nullable<int> id, string internalID, Nullable<int> role, string firstName, string lastName, string password, string email, string phone)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var internalIDParameter = internalID != null ?
                new ObjectParameter("internalID", internalID) :
                new ObjectParameter("internalID", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPerson", idParameter, internalIDParameter, roleParameter, firstNameParameter, lastNameParameter, passwordParameter, emailParameter, phoneParameter);
        }
    
        public virtual int pr_modifyPersonInfoByID(Nullable<int> id, string firstName, string lastName, string title, Nullable<int> role, string phone, string email)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPersonInfoByID", idParameter, firstNameParameter, lastNameParameter, titleParameter, roleParameter, phoneParameter, emailParameter);
        }
    
        public virtual int pr_modifyPersonIsArchivedByID(Nullable<int> id, Nullable<int> isArchived)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var isArchivedParameter = isArchived.HasValue ?
                new ObjectParameter("isArchived", isArchived) :
                new ObjectParameter("isArchived", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPersonIsArchivedByID", idParameter, isArchivedParameter);
        }
    
        public virtual int pr_modifyPersonManager(Nullable<int> id, Nullable<int> manager)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var managerParameter = manager.HasValue ?
                new ObjectParameter("manager", manager) :
                new ObjectParameter("manager", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPersonManager", idParameter, managerParameter);
        }
    
        public virtual int pr_modifyPersonPasswordByID(Nullable<int> id, string pwd)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPersonPasswordByID", idParameter, pwdParameter);
        }
    
        public virtual int pr_modifyPersonStatus(string description, Nullable<int> sortOrder, Nullable<bool> active, Nullable<int> id)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPersonStatus", descriptionParameter, sortOrderParameter, activeParameter, idParameter);
        }
    
        public virtual int pr_modifyPersonStatusByID(Nullable<int> id, Nullable<int> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPersonStatusByID", idParameter, statusParameter);
        }
    
        public virtual int pr_modifyPersonStatusByLoadHistory(Nullable<int> loadHistory, Nullable<int> status)
        {
            var loadHistoryParameter = loadHistory.HasValue ?
                new ObjectParameter("loadHistory", loadHistory) :
                new ObjectParameter("loadHistory", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyPersonStatusByLoadHistory", loadHistoryParameter, statusParameter);
        }
    
        public virtual int pr_modifyRole(string description, Nullable<int> sortOrder, Nullable<int> active, Nullable<int> accessLevel, Nullable<int> enterprise, Nullable<int> access, Nullable<int> id)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(int));
    
            var accessLevelParameter = accessLevel.HasValue ?
                new ObjectParameter("accessLevel", accessLevel) :
                new ObjectParameter("accessLevel", typeof(int));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("enterprise", enterprise) :
                new ObjectParameter("enterprise", typeof(int));
    
            var accessParameter = access.HasValue ?
                new ObjectParameter("access", access) :
                new ObjectParameter("access", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyRole", descriptionParameter, sortOrderParameter, activeParameter, accessLevelParameter, enterpriseParameter, accessParameter, idParameter);
        }
    
        public virtual int pr_modifySystemExpiry(Nullable<System.DateTime> systemExpiry)
        {
            var systemExpiryParameter = systemExpiry.HasValue ?
                new ObjectParameter("systemExpiry", systemExpiry) :
                new ObjectParameter("systemExpiry", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifySystemExpiry", systemExpiryParameter);
        }
    
        public virtual int pr_modifyUserRole(Nullable<int> id, string userRole, Nullable<int> access, Nullable<int> accessLevel)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            var accessParameter = access.HasValue ?
                new ObjectParameter("access", access) :
                new ObjectParameter("access", typeof(int));
    
            var accessLevelParameter = accessLevel.HasValue ?
                new ObjectParameter("accessLevel", accessLevel) :
                new ObjectParameter("accessLevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_modifyUserRole", idParameter, userRoleParameter, accessParameter, accessLevelParameter);
        }
    
        public virtual int pr_removeEnterprise(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_removeEnterprise", idParameter);
        }
    
        public virtual int pr_removeEnterpriseSystemInfo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_removeEnterpriseSystemInfo", idParameter);
        }
    
        public virtual int pr_removePerson(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_removePerson", idParameter);
        }
    
        public virtual int pr_removePersonStatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_removePersonStatus", idParameter);
        }
    
        public virtual int pr_removeRole(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_removeRole", idParameter);
        }
    
        public virtual int pr_removeUserRole(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_removeUserRole", idParameter);
        }
    
        public virtual int pr_unArchiveEnterprise(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_unArchiveEnterprise", idParameter);
        }
    
        public virtual int pr_unArchivePersonStatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_unArchivePersonStatus", idParameter);
        }
    
        public virtual int pr_unArchiveRole(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_unArchiveRole", idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int xx_generateSPforInsertUpdateDelete2(string schemaname, string tablename, string procName, Nullable<bool> identityInsert)
        {
            var schemanameParameter = schemaname != null ?
                new ObjectParameter("Schemaname", schemaname) :
                new ObjectParameter("Schemaname", typeof(string));
    
            var tablenameParameter = tablename != null ?
                new ObjectParameter("Tablename", tablename) :
                new ObjectParameter("Tablename", typeof(string));
    
            var procNameParameter = procName != null ?
                new ObjectParameter("ProcName", procName) :
                new ObjectParameter("ProcName", typeof(string));
    
            var identityInsertParameter = identityInsert.HasValue ?
                new ObjectParameter("IdentityInsert", identityInsert) :
                new ObjectParameter("IdentityInsert", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xx_generateSPforInsertUpdateDelete2", schemanameParameter, tablenameParameter, procNameParameter, identityInsertParameter);
        }
    
        public virtual ObjectResult<xx_getLastDBModified_Result> xx_getLastDBModified()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xx_getLastDBModified_Result>("xx_getLastDBModified");
        }
    }
}
