//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class industryFocus
    {
        public int industry { get; set; }
        public int focus { get; set; }
        public int enterprise { get; set; }
        public string description { get; set; }
        public byte[] pdf { get; set; }
        public bool active { get; set; }
        public Nullable<int> partnertypetouchpointquestionnaire { get; set; }
    }
}
