//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class invalidZcode
    {
        public int id { get; set; }
        public int ptq { get; set; }
        public string zCode { get; set; }
        public int zCodeActionType { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    }
}
