//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class iterateEmailText
    {
        public int id { get; set; }
        public int person { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string footer1 { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
        public string attachmentOneName { get; set; }
        public byte[] attachementOne { get; set; }
        public string attachmentTwoName { get; set; }
        public byte[] attachementTwo { get; set; }
    }
}
