//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class iterateArchive
    {
        public int partner { get; set; }
        public int status { get; set; }
        public int lastContact { get; set; }
        public System.DateTime lastContactDate { get; set; }
        public int previousContact { get; set; }
        public System.DateTime previousContactDate { get; set; }
        public int nextAction { get; set; }
        public System.DateTime nextActionDate { get; set; }
    }
}
