//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class iteratePerson
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public int iteratePartner { get; set; }
        public Nullable<int> lastContact { get; set; }
        public Nullable<System.DateTime> lastContactDate { get; set; }
        public Nullable<int> previousContact { get; set; }
        public Nullable<System.DateTime> previousContactDate { get; set; }
        public Nullable<int> nextAction { get; set; }
        public Nullable<System.DateTime> nextActionDate { get; set; }
        public Nullable<bool> notes { get; set; }
    
        public virtual iteratePartner iteratePartner1 { get; set; }
    }
}
