//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class iteratePartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iteratePartner()
        {
            this.iteratePerson = new HashSet<iteratePerson>();
        }
    
        public int id { get; set; }
        public string internalID { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
        public string dunsnumber { get; set; }
        public string federalID { get; set; }
        public Nullable<int> numberOfEmployees { get; set; }
        public Nullable<int> annualRevenue { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> owner { get; set; }
        public Nullable<int> author { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public int person { get; set; }
        public Nullable<System.Guid> note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iteratePerson> iteratePerson { get; set; }
    }
}
