//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public language()
        {
            this.questionLanguage = new HashSet<questionLanguage>();
            this.questionTranslation = new HashSet<questionTranslation>();
            this.responseTranslation = new HashSet<responseTranslation>();
            this.response = new HashSet<response>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string originalName { get; set; }
        public byte[] flagImage { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> enterprise { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionLanguage> questionLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionTranslation> questionTranslation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<responseTranslation> responseTranslation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<response> response { get; set; }
    }
}
