//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.questionTranslation = new HashSet<questionTranslation>();
            this.responseTranslation = new HashSet<responseTranslation>();
            this.question = new HashSet<question>();
            this.response = new HashSet<response>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string originalName { get; set; }
        public byte[] flagImage { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> enterprise { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        public virtual ICollection<questionTranslation> questionTranslation { get; set; }
        public virtual ICollection<responseTranslation> responseTranslation { get; set; }
        public virtual ICollection<question> question { get; set; }
        public virtual ICollection<response> response { get; set; }
    }
}
