//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class linkedInFullProfile
    {
        public int id { get; set; }
        public string linkedInID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string formattedName { get; set; }
        public string location { get; set; }
        public string country { get; set; }
        public string industry { get; set; }
        public string submittedURL { get; set; }
        public string resolvedURL { get; set; }
        public string title { get; set; }
        public string submittedImageURL { get; set; }
        public string thumbnailURL { get; set; }
        public string eyebrowURL { get; set; }
        public Nullable<int> numberOfConnections { get; set; }
        public string positionTitle { get; set; }
        public string summary { get; set; }
        public Nullable<int> startDateYear { get; set; }
        public Nullable<int> startDateMonth { get; set; }
        public string positionName { get; set; }
        public string pictureURL { get; set; }
        public string linkedInURL { get; set; }
        public string publicProfileURL { get; set; }
        public string emailAddress { get; set; }
        public Nullable<int> person { get; set; }
    }
}
