//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loadHistory
    {
        public int id { get; set; }
        public int person { get; set; }
        public System.DateTime uploadDate { get; set; }
        public Nullable<int> recordcount { get; set; }
        public Nullable<int> type { get; set; }
        public string oldInt { get; set; }
    }
}
