//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class logConfirmedOrphanedPPTQ
    {
        public int id { get; set; }
        public int pptq { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<int> person { get; set; }
    }
}
