//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public page()
        {
            this.surveyset = new HashSet<surveyset>();
            this.questionnaire = new HashSet<questionnaire>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<surveyset> surveyset { get; set; }
        public virtual ICollection<questionnaire> questionnaire { get; set; }
    }
}
