//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerShadow
    {
        public int reference { get; set; }
        public int shadow { get; set; }
        public int group { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<int> EPLSStatus { get; set; }
        public Nullable<int> loadHistory { get; set; }
        public Nullable<int> partnerType { get; set; }
        public string internalID { get; set; }
        public string name { get; set; }
        public int type { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string zipcode { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string dunsNumber { get; set; }
        public string federalID { get; set; }
        public string accessCode { get; set; }
        public string HROFirstName { get; set; }
        public string HROLastName { get; set; }
        public string HROPhone { get; set; }
        public string HROEmail { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> owner { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public Nullable<int> isArchived { get; set; }
        public Nullable<int> EPLSCheckedBy { get; set; }
        public Nullable<System.DateTime> EPLSCheckedDate { get; set; }
        public string remitAddress1 { get; set; }
        public string remitAddress2 { get; set; }
        public string remitCity { get; set; }
        public Nullable<int> remitState { get; set; }
        public string remitProvince { get; set; }
        public string remitZipCode { get; set; }
        public Nullable<int> remitCountry { get; set; }
        public string naicsCode { get; set; }
        public string zcode { get; set; }
        public string businessOwner { get; set; }
        public string name2 { get; set; }
        public string ssn { get; set; }
        public Nullable<bool> corp { get; set; }
        public Nullable<bool> taxExemptEntity { get; set; }
        public Nullable<bool> us { get; set; }
        public Nullable<bool> astate { get; set; }
        public Nullable<bool> foreignGovernment { get; set; }
        public string w9Person { get; set; }
        public string w9Title { get; set; }
        public string w9AuthorizedSignature { get; set; }
        public Nullable<System.DateTime> w9DateSigned { get; set; }
        public string w9Phone { get; set; }
        public string w9Address { get; set; }
        public string w9City { get; set; }
        public Nullable<int> w9State { get; set; }
        public string w9ZipCode { get; set; }
        public string businessDescription { get; set; }
        public Nullable<int> zDec { get; set; }
    }
}
