//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerPartnerTypeTouchpoint
    {
        public int partner { get; set; }
        public int partnerType { get; set; }
        public int touchpoint { get; set; }
    
        public virtual partner partner1 { get; set; }
        public virtual partnerType partnerType1 { get; set; }
        public virtual touchpoint touchpoint1 { get; set; }
    }
}
