//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerReference
    {
        public int id { get; set; }
        public int partner { get; set; }
        public Nullable<int> referenceNumber { get; set; }
        public string companyName { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<bool> @checked { get; set; }
        public string checkedBy { get; set; }
        public Nullable<System.DateTime> dateChecked { get; set; }
        public string notes { get; set; }
    }
}
