//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerProtocolTouchpointQuestionnaireSurveyQuestionResponse
    {
        public int partner { get; set; }
        public int protocol { get; set; }
        public int touchpoint { get; set; }
        public int questionnaire { get; set; }
        public int survey { get; set; }
        public int question { get; set; }
        public Nullable<int> response { get; set; }
        public string comment { get; set; }
        public string uploadedFile { get; set; }
        public Nullable<int> actualScore { get; set; }
    }
}
