//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partnumber()
        {
            this.partNumberSiteZcodePPTQ = new HashSet<partNumberSiteZcodePPTQ>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string internalId { get; set; }
        public string nationalStockingNumber { get; set; }
        public string sapID { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public bool active { get; set; }
        public int partner { get; set; }
    
        public virtual partner partner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partNumberSiteZcodePPTQ> partNumberSiteZcodePPTQ { get; set; }
    }
}
