//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerPartnertypeTouchpointQuestionnaireQuestionResponse
    {
        public int id { get; set; }
        public int question { get; set; }
        public Nullable<int> response { get; set; }
        public string comment { get; set; }
        public byte[] uploadedFile { get; set; }
        public string uploadedFileType { get; set; }
        public Nullable<System.DateTime> actionDate { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> partnerPartnerTypeTouchpointQuestionnaire { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public byte[] commentEncrypted { get; set; }
    
        public virtual partnerPartnertypeTouchpointQuestionnaire partnerPartnertypeTouchpointQuestionnaire1 { get; set; }
        public virtual response response1 { get; set; }
    }
}
