//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerPartnertypeTouchpointQuestionnaire
    {
        public partnerPartnertypeTouchpointQuestionnaire()
        {
            this.eSignature = new HashSet<eSignature>();
            this.partnerPartnertypeTouchpointQuestionnaireQuestionResponse = new HashSet<partnerPartnertypeTouchpointQuestionnaireQuestionResponse>();
            this.partNumberSiteZcodePPTQ = new HashSet<partNumberSiteZcodePPTQ>();
            this.automailMessagePPTQ = new HashSet<automailMessagePPTQ>();
            this.pptqAutoMailMessageLog = new HashSet<pptqAutoMailMessageLog>();
        }
    
        public int id { get; set; }
        public int partner { get; set; }
        public int partnerTypeTouchpointQuestionnaire { get; set; }
        public string accesscode { get; set; }
        public int invitedBy { get; set; }
        public System.DateTime invitedDate { get; set; }
        public Nullable<System.DateTime> completedDate { get; set; }
        public Nullable<int> progress { get; set; }
        public string zcode { get; set; }
        public byte[] pdf { get; set; }
        public string docFolderAddress { get; set; }
        public Nullable<decimal> score { get; set; }
        public int status { get; set; }
        public string loadGroup { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> priority { get; set; }
    
        public virtual ICollection<eSignature> eSignature { get; set; }
        public virtual partner partner1 { get; set; }
        public virtual partnerTypeTouchpointQuestionnaire partnerTypeTouchpointQuestionnaire1 { get; set; }
        public virtual person person { get; set; }
        public virtual ICollection<partnerPartnertypeTouchpointQuestionnaireQuestionResponse> partnerPartnertypeTouchpointQuestionnaireQuestionResponse { get; set; }
        public virtual ICollection<partNumberSiteZcodePPTQ> partNumberSiteZcodePPTQ { get; set; }
        public virtual ICollection<automailMessagePPTQ> automailMessagePPTQ { get; set; }
        public virtual partnerStatus partnerStatus { get; set; }
        public virtual ICollection<pptqAutoMailMessageLog> pptqAutoMailMessageLog { get; set; }
    }
}
