//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerCorpInfo
    {
        public int partner { get; set; }
        public string businessDescription { get; set; }
        public string taxExemptId { get; set; }
        public string alias { get; set; }
        public string ssn { get; set; }
        public Nullable<bool> corp { get; set; }
        public Nullable<bool> taxExemptEntity { get; set; }
        public Nullable<bool> us { get; set; }
        public Nullable<bool> astate { get; set; }
        public Nullable<bool> foreignGovernment { get; set; }
        public string naicsCode { get; set; }
    
        public virtual partner partner1 { get; set; }
    }
}
