//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerSpendAmount
    {
        public int id { get; set; }
        public int partner { get; set; }
        public Nullable<decimal> spendAmount { get; set; }
        public Nullable<System.DateTime> ytd { get; set; }
        public Nullable<System.DateTime> dateTimeStmp { get; set; }
    }
}
