//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partner()
        {
            this.partnerPartnertypeTouchpointQuestionnaire = new HashSet<partnerPartnertypeTouchpointQuestionnaire>();
            this.partnerTouchpointInvitedDate_deprecated = new HashSet<partnerTouchpointInvitedDate_deprecated>();
            this.partnerTouchpointQuestionnaireLanguage = new HashSet<partnerTouchpointQuestionnaireLanguage>();
            this.group = new HashSet<group>();
            this.person = new HashSet<person>();
            this.partnumber = new HashSet<partnumber>();
        }
    
        public int id { get; set; }
        public Nullable<int> enterprise { get; set; }
        public string internalID { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public Nullable<int> state { get; set; }
        public string province { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> country { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string dunsNumber { get; set; }
        public string federalID { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> loadHistory { get; set; }
        public Nullable<int> owner { get; set; }
        public Nullable<int> author { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        public virtual partnerCorpInfo partnerCorpInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnerPartnertypeTouchpointQuestionnaire> partnerPartnertypeTouchpointQuestionnaire { get; set; }
        public virtual partnerRemitAddress partnerRemitAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnerTouchpointInvitedDate_deprecated> partnerTouchpointInvitedDate_deprecated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnerTouchpointQuestionnaireLanguage> partnerTouchpointQuestionnaireLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group> group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<person> person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnumber> partnumber { get; set; }
    }
}
