//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerSpreadsheetDataLoad
    {
        public int id { get; set; }
        public string partner_internal_id { get; set; }
        public string partner_sap_id { get; set; }
        public string partner_name { get; set; }
        public string partner_address_one { get; set; }
        public string partner_address_two { get; set; }
        public string partner_city { get; set; }
        public string partner_state { get; set; }
        public string partner_zipcode { get; set; }
        public string partner_country { get; set; }
        public string partner_poc_first_name { get; set; }
        public string partner_poc_last_name { get; set; }
        public string partner_poc_title { get; set; }
        public string partner_poc_phone_number { get; set; }
        public string partner_poc_email_address { get; set; }
        public string ro_first_name { get; set; }
        public string ro_last_name { get; set; }
        public string ro_email { get; set; }
        public Nullable<System.DateTime> date_loaded { get; set; }
        public int enterprise { get; set; }
        public int partnertype { get; set; }
        public int touchpoint { get; set; }
        public int person { get; set; }
        public Nullable<int> partnerSpreadsheetDataLoadStatus { get; set; }
        public string loadGroup { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        public virtual partnerType partnerType1 { get; set; }
        public virtual person person1 { get; set; }
        public virtual touchpoint touchpoint1 { get; set; }
    }
}
