//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerReport
    {
        public int partner_id { get; set; }
        public string partner { get; set; }
        public int partnerType_id { get; set; }
        public int partnerStatus_id { get; set; }
        public int touchpoint_id { get; set; }
        public int group_id { get; set; }
        public int country_id { get; set; }
        public string partnerType { get; set; }
        public string partnerStatus { get; set; }
        public string touchpoint { get; set; }
        public string group { get; set; }
        public string country { get; set; }
    }
}
