//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerTouchpointStatus
    {
        public int partner { get; set; }
        public int touchpoint { get; set; }
        public int status { get; set; }
        public string accesscode { get; set; }
        public Nullable<int> actor { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> invitedDate { get; set; }
        public Nullable<System.DateTime> completeDate { get; set; }
        public Nullable<decimal> SCSII { get; set; }
        public Nullable<int> progress { get; set; }
    
        public virtual partner partner1 { get; set; }
        public virtual touchpoint touchpoint1 { get; set; }
    }
}
