//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerRemitAddress
    {
        public int partner { get; set; }
        public string remitAddress1 { get; set; }
        public string remitAddress2 { get; set; }
        public string remitCity { get; set; }
        public Nullable<int> remitState { get; set; }
        public string remitProvince { get; set; }
        public string remitZipCode { get; set; }
        public Nullable<int> remitCountry { get; set; }
    
        public virtual partner partner1 { get; set; }
    }
}
