//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partNumberSiteZcodePPTQ
    {
        public partNumberSiteZcodePPTQ()
        {
            this.partnumberSiteZcodePPTQQuestionResponse = new HashSet<partnumberSiteZcodePPTQQuestionResponse>();
        }
    
        public int id { get; set; }
        public int partnumber { get; set; }
        public int site { get; set; }
        public string zcode { get; set; }
        public int status { get; set; }
        public int partnerPartnertypeTouchpointQuestionnaire { get; set; }
    
        public virtual partnerPartnertypeTouchpointQuestionnaire partnerPartnertypeTouchpointQuestionnaire1 { get; set; }
        public virtual partnumber partnumber1 { get; set; }
        public virtual partnumberStatus partnumberStatus { get; set; }
        public virtual site site1 { get; set; }
        public virtual ICollection<partnumberSiteZcodePPTQQuestionResponse> partnumberSiteZcodePPTQQuestionResponse { get; set; }
    }
}
