//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerLogin
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string passWord { get; set; }
        public string internalId { get; set; }
        public Nullable<int> status { get; set; }
    }
}
