//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerActionLog
    {
        public int id { get; set; }
        public Nullable<int> partner { get; set; }
        public Nullable<int> action { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string comment { get; set; }
    }
}
