//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerTemp
    {
        public int id { get; set; }
        public string internalID { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string province { get; set; }
        public string PostalCode { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string dunsNumber { get; set; }
        public string federalID { get; set; }
        public string HROFirstName { get; set; }
        public string HROLastName { get; set; }
        public string HROPhone { get; set; }
        public string HROEmail { get; set; }
        public int loadHistory { get; set; }
        public Nullable<int> badRecordType { get; set; }
    }
}
