//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerTypeTouchpointQuestionnaire
    {
        public partnerTypeTouchpointQuestionnaire()
        {
            this.autoMailMessage = new HashSet<autoMailMessage>();
            this.partnerPartnertypeTouchpointQuestionnaire = new HashSet<partnerPartnertypeTouchpointQuestionnaire>();
        }
    
        public int id { get; set; }
        public int partnerType { get; set; }
        public int touchpoint { get; set; }
        public int questionnaire { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<autoMailMessage> autoMailMessage { get; set; }
        public virtual ICollection<partnerPartnertypeTouchpointQuestionnaire> partnerPartnertypeTouchpointQuestionnaire { get; set; }
        public virtual partnerType partnerType1 { get; set; }
        public virtual questionnaire questionnaire1 { get; set; }
        public virtual touchpoint touchpoint1 { get; set; }
        public virtual questionnaire questionnaire2 { get; set; }
        public virtual touchpoint touchpoint2 { get; set; }
    }
}
