//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.group = new HashSet<group>();
            this.partnerPartnertypeTouchpointQuestionnaire = new HashSet<partnerPartnertypeTouchpointQuestionnaire>();
            this.personLoginAudit = new HashSet<personLoginAudit>();
            this.personRelationship = new HashSet<personRelationship>();
            this.personRelationship1 = new HashSet<personRelationship>();
            this.personRelationship2 = new HashSet<personRelationship>();
            this.personSearchCount = new HashSet<personSearchCount>();
            this.protocol = new HashSet<protocol>();
            this.protocol1 = new HashSet<protocol>();
            this.partner = new HashSet<partner>();
            this.group1 = new HashSet<group>();
            this.role = new HashSet<role>();
        }
    
        public int id { get; set; }
        public Nullable<int> enterprise { get; set; }
        public Nullable<int> manager { get; set; }
        public Nullable<int> personStatus { get; set; }
        public Nullable<int> riskType { get; set; }
        public Nullable<int> loadHistory { get; set; }
        public Nullable<int> campaign { get; set; }
        public string internalId { get; set; }
        public string nmNumber { get; set; }
        public string socialSecurity { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string suffix { get; set; }
        public string nickName { get; set; }
        public string passWord { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public Nullable<int> state { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> country { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> ismanager { get; set; }
        public Nullable<int> partnerPerPage { get; set; }
        public Nullable<System.DateTime> resetDate { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<System.DateTime> archivedDate { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        public virtual ICollection<group> group { get; set; }
        public virtual ICollection<partnerPartnertypeTouchpointQuestionnaire> partnerPartnertypeTouchpointQuestionnaire { get; set; }
        public virtual personStatus personStatus1 { get; set; }
        public virtual ICollection<personLoginAudit> personLoginAudit { get; set; }
        public virtual ICollection<personRelationship> personRelationship { get; set; }
        public virtual ICollection<personRelationship> personRelationship1 { get; set; }
        public virtual ICollection<personRelationship> personRelationship2 { get; set; }
        public virtual ICollection<personSearchCount> personSearchCount { get; set; }
        public virtual ICollection<protocol> protocol { get; set; }
        public virtual ICollection<protocol> protocol1 { get; set; }
        public virtual ICollection<partner> partner { get; set; }
        public virtual ICollection<group> group1 { get; set; }
        public virtual ICollection<role> role { get; set; }
    }
}
