//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class personLoginAudit
    {
        public int id { get; set; }
        public int person { get; set; }
        public int auditLoginEvent { get; set; }
        public System.DateTime timestamp { get; set; }
        public string deviceIP { get; set; }
    
        public virtual person person1 { get; set; }
        public virtual personLoginAuditEvent personLoginAuditEvent { get; set; }
    }
}
