//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class personSignature
    {
        public int person { get; set; }
        public string footer2 { get; set; }
        public byte[] eSignature { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public bool active { get; set; }
    }
}
