//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class personSearchCount
    {
        public int id { get; set; }
        public int person { get; set; }
        public System.DateTime queryDateTime { get; set; }
        public Nullable<long> countSearch { get; set; }
    
        public virtual person person1 { get; set; }
    }
}
