//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class personLinkedinAuthInfo
    {
        public int id { get; set; }
        public string token { get; set; }
        public string tokenSecret { get; set; }
        public string verifier { get; set; }
        public int person { get; set; }
    
        public virtual person person1 { get; set; }
    }
}
