//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class personRelationship
    {
        public int personIsThe { get; set; }
        public int personHasThe { get; set; }
        public int RelationshipTypeID { get; set; }
    
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
        public virtual person person2 { get; set; }
        public virtual personRelationshipType personRelationshipType { get; set; }
    }
}
