//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class pptqGroup
    {
        public int pptq { get; set; }
        public int group { get; set; }
        public Nullable<int> pptqGroupType { get; set; }
        public Nullable<bool> isShadow { get; set; }
        public Nullable<int> pptqReference { get; set; }
        public Nullable<int> changedBy { get; set; }
        public Nullable<System.DateTime> changedAt { get; set; }
    }
}
