//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class pptqAutoMailMessageLog
    {
        public int id { get; set; }
        public int pptq { get; set; }
        public int autoMailMessage { get; set; }
        public System.DateTime sendDate { get; set; }
    }
}
