//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class pptqDoc
    {
        public int id { get; set; }
        public int pptq { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte[] doc { get; set; }
        public int doctype { get; set; }
        public System.DateTime uploadDateTime { get; set; }
        public int uploadedBy { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public bool active { get; set; }
    }
}
