//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    
    public partial class pr_getPersonPPTQClauseAll_Result1
    {
        public int id { get; set; }
        public int person { get; set; }
        public int pptq { get; set; }
        public int clause { get; set; }
        public int status { get; set; }
        public System.DateTime dateAssigned { get; set; }
        public Nullable<System.DateTime> dateDue { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
        public byte[] dataFile { get; set; }
        public string comment { get; set; }
        public string note { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    }
}
