//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    
    public partial class pr_getEventNotificationBounce_Result1
    {
        public string email { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string @event { get; set; }
        public string reason { get; set; }
        public string protocoltouchpoint { get; set; }
        public string accesscode { get; set; }
        public string link { get; set; }
    }
}
