//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class query
    {
        public int id { get; set; }
        public string description { get; set; }
        public string sqlText { get; set; }
        public int author { get; set; }
        public int questionnaire { get; set; }
        public Nullable<int> status { get; set; }
    }
}
