//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class queryFieldQuestion
    {
        public int query { get; set; }
        public int question { get; set; }
        public string response { get; set; }
        public Nullable<int> isText { get; set; }
    }
}
