//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaireLoad
    {
        public int id { get; set; }
        public int qid { get; set; }
        public int page { get; set; }
        public string surveySet { get; set; }
        public string survey { get; set; }
        public string question { get; set; }
        public string response { get; set; }
        public string comment { get; set; }
        public string title { get; set; }
        public string required { get; set; }
        public int length { get; set; }
        public int titleLength { get; set; }
        public int yValue { get; set; }
        public int nValue { get; set; }
        public int otherValue { get; set; }
        public int qWeight { get; set; }
        public string skipLogic { get; set; }
        public string skipLogicAnswer { get; set; }
        public string skipLogicJump { get; set; }
        public string commentBoxMessageText { get; set; }
        public string uploadMessageText { get; set; }
        public string commentType { get; set; }
        public string spinOffQuestionnaire { get; set; }
        public int spinOffID { get; set; }
        public string emailAlert { get; set; }
        public string emailAlertList { get; set; }
        public int questionnaire { get; set; }
        public string subCheckBoxChoice { get; set; }
        public string calendarMessageText { get; set; }
    }
}
