//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question()
        {
            this.partnumberSiteZcodePPTQQuestionResponses = new HashSet<partnumberSiteZcodePPTQQuestionResponse>();
            this.questionResponses = new HashSet<questionResponse>();
            this.questionResponses1 = new HashSet<questionResponse>();
            this.questionTranslations = new HashSet<questionTranslation>();
            this.surveys = new HashSet<survey>();
        }
    
        public int id { get; set; }
        public string Question { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string tag { get; set; }
        public Nullable<int> responseType { get; set; }
        public Nullable<int> required { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> skipLogicAnswer { get; set; }
        public string skipLogicJump { get; set; }
        public Nullable<int> accessLevel { get; set; }
        public Nullable<int> commentRequired { get; set; }
        public string commentBoxTxt { get; set; }
        public string commentUploadTxt { get; set; }
        public Nullable<int> commentType { get; set; }
        public string calendarMessageTxt { get; set; }
        public string spinOffQuestionnaire { get; set; }
        public Nullable<int> spinOffQID { get; set; }
        public string emailAlert { get; set; }
        public string emailAlertList { get; set; }
        public Nullable<int> updated { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> enterprise { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnumberSiteZcodePPTQQuestionResponse> partnumberSiteZcodePPTQQuestionResponses { get; set; }
        public virtual responseType responseType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionResponse> questionResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionResponse> questionResponses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionTranslation> questionTranslations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey> surveys { get; set; }
    }
}
