//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaireRuleActionDateType
    {
        public questionnaireRuleActionDateType()
        {
            this.questionnaireRule = new HashSet<questionnaireRule>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<questionnaireRule> questionnaireRule { get; set; }
    }
}
