//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaireCMSLoad
    {
        public int id { get; set; }
        public int questionnaireCMS { get; set; }
        public string description { get; set; }
        public string text { get; set; }
        public string link { get; set; }
        public int questionnaire { get; set; }
    }
}
