//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionResponse
    {
        public int question { get; set; }
        public int response { get; set; }
    
        public virtual question question1 { get; set; }
        public virtual question question2 { get; set; }
        public virtual response response1 { get; set; }
    }
}
