//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.questionResponse = new HashSet<questionResponse>();
            this.questionResponse1 = new HashSet<questionResponse>();
            this.questionTranslation = new HashSet<questionTranslation>();
            this.language = new HashSet<language>();
        }
    
        public int id { get; set; }
        public string question1 { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string tag { get; set; }
        public Nullable<int> responseType { get; set; }
        public Nullable<int> required { get; set; }
        public Nullable<bool> skipLogicAnswer { get; set; }
        public string skipLogicJump { get; set; }
        public Nullable<int> accessLevel { get; set; }
        public Nullable<int> commentRequired { get; set; }
        public string commentBoxTxt { get; set; }
        public string commentUploadTxt { get; set; }
        public Nullable<int> commentType { get; set; }
        public string spinOffQuestionnaire { get; set; }
        public Nullable<int> spinOffQID { get; set; }
        public string emailAlert { get; set; }
        public string emailAlertList { get; set; }
        public Nullable<int> updated { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> enterprise { get; set; }
    
        public virtual responseType responseType1 { get; set; }
        public virtual ICollection<questionResponse> questionResponse { get; set; }
        public virtual ICollection<questionResponse> questionResponse1 { get; set; }
        public virtual ICollection<questionTranslation> questionTranslation { get; set; }
        public virtual ICollection<language> language { get; set; }
    }
}
