//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaireAutomailMessageLoad
    {
        public int id { get; set; }
        public int rid { get; set; }
        public int type { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string footer { get; set; }
        public string signature { get; set; }
        public int sendDateCalcFactor { get; set; }
        public int questionnaire { get; set; }
    }
}
