//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionResponseNarrativeSelectionList
    {
        public int id { get; set; }
        public int question { get; set; }
        public int questionReference { get; set; }
        public int questionReferenceResponse { get; set; }
        public string subject { get; set; }
        public string narrative { get; set; }
        public int sortOrder { get; set; }
        public bool active { get; set; }
    }
}
