//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaire
    {
        public questionnaire()
        {
            this.page = new HashSet<page>();
            this.partnerTouchpointQuestionnaireQuestionResponse = new HashSet<partnerTouchpointQuestionnaireQuestionResponse>();
            this.partnerTypeTouchpointQuestionnaire = new HashSet<partnerTypeTouchpointQuestionnaire>();
        }
    
        public int id { get; set; }
        public int person { get; set; }
        public int partnerType { get; set; }
        public Nullable<int> letter { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string footer { get; set; }
        public Nullable<int> locked { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> multiLanguage { get; set; }
        public Nullable<int> enterprise { get; set; }
    
        public virtual ICollection<page> page { get; set; }
        public virtual ICollection<partnerTouchpointQuestionnaireQuestionResponse> partnerTouchpointQuestionnaireQuestionResponse { get; set; }
        public virtual ICollection<partnerTypeTouchpointQuestionnaire> partnerTypeTouchpointQuestionnaire { get; set; }
    }
}
