//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaireRule
    {
        public int id { get; set; }
        public string description { get; set; }
        public string zcodePattern { get; set; }
        public string scorePattern { get; set; }
        public int actionType { get; set; }
        public Nullable<int> questionnaireToSend { get; set; }
        public int targetType { get; set; }
        public string targetEmailList { get; set; }
        public int actionDateType { get; set; }
        public Nullable<System.DateTime> actionDateSet { get; set; }
        public int questionnaire { get; set; }
        public bool active { get; set; }
    
        public virtual questionnaire questionnaire1 { get; set; }
        public virtual questionnaire questionnaire2 { get; set; }
        public virtual questionnaireRuleActionDateType questionnaireRuleActionDateType { get; set; }
        public virtual questionnaireRuleTargetType questionnaireRuleTargetType { get; set; }
    }
}
