//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionTranslation
    {
        public int question { get; set; }
        public int language { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    
        public virtual language language1 { get; set; }
        public virtual question question1 { get; set; }
    }
}
