//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;
    
    public partial class questionnaireQuestionnaireCMS
    {
        public int questionnaire { get; set; }
        public int questionnaireCMS { get; set; }
        public string text { get; set; }
        public string link { get; set; }
        public byte[] doc { get; set; }

        [XmlIgnore]
        [IgnoreDataMember]
        public virtual questionnaire questionnaire1 { get; set; }
        [XmlIgnore]
        [IgnoreDataMember]
        public virtual questionnaireCMS questionnaireCMS1 { get; set; }
    }
}
