//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.person = new HashSet<person>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> accessLevel { get; set; }
        public Nullable<int> enterprise { get; set; }
        public Nullable<int> access { get; set; }
    
        public virtual enterprise enterprise1 { get; set; }
        public virtual ICollection<person> person { get; set; }
    }
}
