//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteIP
    {
        public int id { get; set; }
        public int enterprise { get; set; }
        public int site { get; set; }
        public string sitename { get; set; }
        public string siteIPStart { get; set; }
        public string siteIPEnd { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
