//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class swap
    {
        public int id { get; set; }
        public int person { get; set; }
        public string oldInternalID { get; set; }
        public string newInternalID { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> oldId { get; set; }
    }
}
