//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemConfiguration
    {
        public int id { get; set; }
        public Nullable<bool> hasRemitAddress { get; set; }
        public Nullable<bool> hasFederalId { get; set; }
        public Nullable<bool> hasDunsNumber { get; set; }
        public Nullable<bool> hasNaics { get; set; }
        public Nullable<bool> hasBusinessDescription { get; set; }
        public Nullable<bool> hasSpendCategory { get; set; }
        public Nullable<bool> hasReference { get; set; }
        public Nullable<bool> hasRegion { get; set; }
        public Nullable<bool> hasw9Form { get; set; }
    }
}
