//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class touchpoint
    {
        public touchpoint()
        {
            this.partnerTypeTouchpointQuestionnaire = new HashSet<partnerTypeTouchpointQuestionnaire>();
            this.partnerTypeTouchpointQuestionnaire1 = new HashSet<partnerTypeTouchpointQuestionnaire>();
            this.touchpointPartnerRerouter = new HashSet<touchpointPartnerRerouter>();
            this.touchpointPartnerTypeScoreAutoMail = new HashSet<touchpointPartnerTypeScoreAutoMail>();
            this.touchpointQuestionResponseValue_deprecated = new HashSet<touchpointQuestionResponseValue_deprecated>();
            this.touchpointQuestionWeight_deprecated = new HashSet<touchpointQuestionWeight_deprecated>();
            this.questionnaire = new HashSet<questionnaire>();
            this.partnerSpreadsheetDataLoad = new HashSet<partnerSpreadsheetDataLoad>();
            this.partnumberSpreadsheetDataLoad = new HashSet<partnumberSpreadsheetDataLoad>();
        }

        public int id { get; set; }
        [Required]
        public Nullable<int> protocol { get; set; }
        public Nullable<int> person { get; set; }
        [Required]
        public Nullable<int> sponsor { get; set; }
        [Required]
        public Nullable<int> admin { get; set; }
        [Required]
        public string title { get; set; }
        public string description { get; set; }
        public string abbreviation { get; set; }
        [Required]
        public Nullable<System.DateTime> startDate { get; set; }
        [Required]
        public Nullable<System.DateTime> endDate { get; set; }
        [Required]
        public Nullable<bool> automaticReminder { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> active { get; set; }
        public string purpose { get; set; }
        [Required]
        public Nullable<int> target { get; set; }

        public virtual ICollection<partnerTypeTouchpointQuestionnaire> partnerTypeTouchpointQuestionnaire { get; set; }
        public virtual ICollection<partnerTypeTouchpointQuestionnaire> partnerTypeTouchpointQuestionnaire1 { get; set; }
        public virtual protocol protocol1 { get; set; }
        public virtual ICollection<touchpointPartnerRerouter> touchpointPartnerRerouter { get; set; }
        public virtual ICollection<touchpointPartnerTypeScoreAutoMail> touchpointPartnerTypeScoreAutoMail { get; set; }
        public virtual ICollection<touchpointQuestionResponseValue_deprecated> touchpointQuestionResponseValue_deprecated { get; set; }
        public virtual ICollection<touchpointQuestionWeight_deprecated> touchpointQuestionWeight_deprecated { get; set; }
        public virtual ICollection<questionnaire> questionnaire { get; set; }
        public virtual ICollection<partnerSpreadsheetDataLoad> partnerSpreadsheetDataLoad { get; set; }
        public virtual touchpointTarget touchpointTarget { get; set; }
        public virtual ICollection<partnumberSpreadsheetDataLoad> partnumberSpreadsheetDataLoad { get; set; }
    }
}
