//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class touchpoint
    {
        public touchpoint()
        {
            this.partnerTouchpointStatus = new HashSet<partnerTouchpointStatus>();
            this.partnerPartnerTypeTouchpoint = new HashSet<partnerPartnerTypeTouchpoint>();
            this.partnerTouchpointQuestionnaireQuestionResponse = new HashSet<partnerTouchpointQuestionnaireQuestionResponse>();
            this.partnerTypeTouchpointQuestionnaire = new HashSet<partnerTypeTouchpointQuestionnaire>();
            this.touchpointPartnerRerouter = new HashSet<touchpointPartnerRerouter>();
            this.touchpointPartnerTypeScoreAutoMail = new HashSet<touchpointPartnerTypeScoreAutoMail>();
            this.touchpointQuestionResponseValue = new HashSet<touchpointQuestionResponseValue>();
            this.touchpointQuestionWeight = new HashSet<touchpointQuestionWeight>();
        }
    
        public int id { get; set; }
        public Nullable<int> protocol { get; set; }
        public Nullable<int> person { get; set; }
        public Nullable<int> sponsor { get; set; }
        public Nullable<int> admin { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string abbreviation { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<bool> automaticReminder { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual ICollection<partnerTouchpointStatus> partnerTouchpointStatus { get; set; }
        public virtual protocol protocol1 { get; set; }
        public virtual ICollection<partnerPartnerTypeTouchpoint> partnerPartnerTypeTouchpoint { get; set; }
        public virtual ICollection<partnerTouchpointQuestionnaireQuestionResponse> partnerTouchpointQuestionnaireQuestionResponse { get; set; }
        public virtual ICollection<partnerTypeTouchpointQuestionnaire> partnerTypeTouchpointQuestionnaire { get; set; }
        public virtual ICollection<touchpointPartnerRerouter> touchpointPartnerRerouter { get; set; }
        public virtual ICollection<touchpointPartnerTypeScoreAutoMail> touchpointPartnerTypeScoreAutoMail { get; set; }
        public virtual ICollection<touchpointQuestionResponseValue> touchpointQuestionResponseValue { get; set; }
        public virtual ICollection<touchpointQuestionWeight> touchpointQuestionWeight { get; set; }
    }
}
