//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class touchpointPartnerRerouter
    {
        public int touchpoint { get; set; }
        public int partner { get; set; }
        public string fromFirstName { get; set; }
        public string fromLastName { get; set; }
        public string fromTitle { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public Nullable<bool> status { get; set; }
        public System.DateTime timeStamp { get; set; }
    
        public virtual touchpoint touchpoint1 { get; set; }
    }
}
