//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class touchpointPartnerTypeScoreAutoMail
    {
        public int id { get; set; }
        public int touchpoint { get; set; }
        public int partnerType { get; set; }
        public int score { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public Nullable<bool> isSendToPartner { get; set; }
        public Nullable<bool> isSendToUser { get; set; }
    
        public virtual touchpoint touchpoint1 { get; set; }
    }
}
