//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_M_Menu_deprecated
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UM_M_Menu_deprecated()
        {
            this.UM_M_Menu_deprecated1 = new HashSet<UM_M_Menu_deprecated>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> accesslevel { get; set; }
        public Nullable<int> enterprice { get; set; }
    
        public virtual enterprise enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_M_Menu_deprecated> UM_M_Menu_deprecated1 { get; set; }
        public virtual UM_M_Menu_deprecated UM_M_Menu_deprecated2 { get; set; }
    }
}
