//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PartnerFind
    {
        public Nullable<int> enterprise { get; set; }
        public int campaign { get; set; }
        public string group { get; set; }
        public string partnertype { get; set; }
        public string internalID { get; set; }
        public string dunsnumber { get; set; }
        public string federalID { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> country { get; set; }
        public string description { get; set; }
        public int partnerTypeTouchpointQuestionnaire { get; set; }
        public string accesscode { get; set; }
        public System.DateTime invitedDate { get; set; }
        public Nullable<System.DateTime> completedDate { get; set; }
        public int touchpoint { get; set; }
    }
}
