//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PartnerConfirmationData
    {
        public int id { get; set; }
        public int enterprise { get; set; }
        public int touchpoint { get; set; }
        public int Partner_A { get; set; }
        public string partnerA_Name { get; set; }
        public int group1 { get; set; }
        public string group1_Name { get; set; }
        public int status1 { get; set; }
        public string status1_Name { get; set; }
        public bool isReference1 { get; set; }
        public int Partner_B { get; set; }
        public string partnerB_Name { get; set; }
        public int group2 { get; set; }
        public string group2_Name { get; set; }
        public int status2 { get; set; }
        public string status2_Name { get; set; }
        public bool isReference2 { get; set; }
        public bool emailMatch { get; set; }
        public Nullable<bool> nameMatch { get; set; }
        public bool internalIDMatch { get; set; }
        public bool federalIDMatch { get; set; }
        public bool dunsMatch { get; set; }
        public Nullable<int> action { get; set; }
        public Nullable<int> person { get; set; }
        public byte[] timestamp { get; set; }
    }
}
