//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PersonData
    {
        public int id { get; set; }
        public Nullable<int> enterprise { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string internalID { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<int> Default_Touchpoint { get; set; }
        public string Touchpoint { get; set; }
        public Nullable<int> personStatusID { get; set; }
        public string Person_Status { get; set; }
        public Nullable<int> Group_Count { get; set; }
        public Nullable<int> Role_Count { get; set; }
        public Nullable<int> active { get; set; }
    }
}
