//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_GroupData
    {
        public int id { get; set; }
        public Nullable<int> Enterprise { get; set; }
        public string name { get; set; }
        public int UserCount { get; set; }
        public int PartnerCount { get; set; }
        public int ShadowCount { get; set; }
        public int CampaignCount { get; set; }
        public Nullable<int> Active { get; set; }
        public string description { get; set; }
        public string Owner { get; set; }
    }
}
