//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ProtocolData
    {
        public Nullable<int> enterprise { get; set; }
        public string name { get; set; }
        public string Protocol_Admin { get; set; }
        public string Protocol_Sponsor { get; set; }
        public int User_Count { get; set; }
        public int Partner_Count { get; set; }
        public int Group_Count { get; set; }
        public int id { get; set; }
        public Nullable<int> active { get; set; }
    }
}
