//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EnterpriseData
    {
        public int id { get; set; }
        public string description { get; set; }
        public string companyname { get; set; }
        public string instancename { get; set; }
        public Nullable<int> userMax { get; set; }
        public Nullable<int> partnerMax { get; set; }
        public Nullable<int> partnumberMax { get; set; }
        public Nullable<int> productID { get; set; }
        public string product { get; set; }
        public Nullable<int> subscriptiontypeID { get; set; }
        public string subscriptiontype { get; set; }
        public Nullable<int> multitenantprojecttypeID { get; set; }
        public string multitenantprojecttype { get; set; }
    }
}
