//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PersonData
    {
        public int id { get; set; }
        public Nullable<int> enterprise { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string internalId { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<int> Touchpoint { get; set; }
        public string Default_Touchpoint { get; set; }
        public Nullable<int> personStatusID { get; set; }
        public string Person_Status { get; set; }
        public Nullable<int> Group_Count { get; set; }
        public Nullable<int> Role_Count { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> resetDate { get; set; }
        public Nullable<System.DateTime> archivedDate { get; set; }
    }
}
