//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_QuestionnaireData
    {
        public Nullable<int> enterprise { get; set; }
        public string Protocol { get; set; }
        public string Touchpoint { get; set; }
        public string PartnerType { get; set; }
        public string Author { get; set; }
        public string Locked { get; set; }
        public int Completed { get; set; }
        public int Incomplete { get; set; }
        public int No_Response { get; set; }
        public string CMS { get; set; }
        public string Reminders { get; set; }
        public int protocolID { get; set; }
        public int touchpointid { get; set; }
        public int questionnaireId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int partnertypeid { get; set; }
        public int personID { get; set; }
    }
}
