//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EventNotificationData
    {
        public Nullable<int> enterprise { get; set; }
        public int mailtype { get; set; }
        public string description { get; set; }
        public System.DateTime Date_Sent { get; set; }
        public int partner { get; set; }
        public int partnertypetouchpointquestionnaire { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string @event { get; set; }
        public int partnerID { get; set; }
    }
}
