//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PartnerConfirmationData_tmp
    {
        public Nullable<long> id { get; set; }
        public Nullable<int> enterprise { get; set; }
        public int touchpoint { get; set; }
        public int Partner_A { get; set; }
        public string Partner_A_Name { get; set; }
        public int Group1ID { get; set; }
        public string Group1 { get; set; }
        public int StatusID_1 { get; set; }
        public string Status1 { get; set; }
        public string IsReference1 { get; set; }
        public int Partner_B { get; set; }
        public string Partner_B_Name { get; set; }
        public int Group2ID { get; set; }
        public string Group2 { get; set; }
        public int StatusID_2 { get; set; }
        public string Status2 { get; set; }
        public string IsReference2 { get; set; }
        public string EmailMatch { get; set; }
        public string InternalIDMatch { get; set; }
        public string FederalIDMatch { get; set; }
        public string DUNSMatch { get; set; }
        public string NameMatch { get; set; }
        public int person { get; set; }
        public int action { get; set; }
        public Nullable<System.Guid> timestamp { get; set; }
    }
}
