//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic
{
    using System;
    using System.Collections.Generic;
    
    public partial class zCodeBatchUpdate
    {
        public int id { get; set; }
        public string internalId { get; set; }
        public string federalId { get; set; }
        public string zcode { get; set; }
        public string dunsnumber { get; set; }
        public Nullable<int> loadhistory { get; set; }
    }
}
